services:
  ecomm:
    build: .
    image: laurobezerra/ecomm:1.0
    container_name: ecomm
  
  mongo-ecomm:
    image: mongo
    container_name: mongo-ecomm
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_HOST_PROD: mongo-ecomm
    volumes:
      - db-mongo-ecomm:/data/db
      - type: bind
        source: ./mongo
        target: /mongo-scripts

volumes:
  db-mongo-ecomm:
    driver: local