openapi: 3.0.1
info:
  title: API - ecomm
  description: API para manipular dados do ecommerce Ecomm.
  version: 0.0.1
  contact:
    name: Ecomm
    url: https://github.com/brashi/ecomm
  license:
    name: "Licença MIT"
    url: https://www.mit.edu/~amini/LICENSE.md
servers:
- url: http://localhost:3000
  description: json-server rodando localmente
paths:
  /api/categories:
    get:
      summary: Recupera todas as categorias cadastradas
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/categories"
        404:
          description: "Categorias não encontradas"
          content:
            application/json:
              example: "Not Found"
  /api/admin/categories:  
    post:
      summary: Cria nova categoria
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
  /api/categories/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Recupera uma entidade pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not Found"
components:
  schemas:
    category:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        status:
          type: string
    categories:
      type: array
      items:
        $ref: "#/components/schemas/category"