openapi: 3.0.1
info:
  title: API - ecomm
  description: API para manipular dados do ecommerce Ecomm.
  version: 0.0.1
  contact:
    name: Ecomm
    url: https://github.com/brashi/ecomm
  license:
    name: "Licença MIT"
    url: https://www.mit.edu/~amini/LICENSE.md
servers:
- url: http://localhost:3000
  description: json-server rodando localmente
tags:
  - name: Categorias
    description: Endpoints de Categorias
  - name: Produtos
    description: Endpoints de Produtos
paths:
  /api/categories:
    get:
      tags:
        - Categorias
      summary: Recupera todas as categorias cadastradas
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/categories"
        404:
          description: "Categorias não encontradas"
          content:
            application/json:
              example: "Not Found"
  /api/categories/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      tags:
        - Categorias
      summary: Recupera uma entidade pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not Found"
  /api/admin/categories:  
    post:
      tags: 
        - Categorias
      summary: Cria nova categoria
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
  /api/admin/categories/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    put:
      tags:
        - Categorias
      summary: Alterar dados da categoria.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/putCategory"
      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not Found"
    delete:
      tags:
        - Categorias
      summary: Deleta a categoria.
      responses:
        200:
          description: Categoria removida.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
        404:
          description: Categoria não encontrada.
  /api/admin/categories/{id}/update:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    put:
      tags:
        - Categorias
      summary: Altera status da categoria
      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
  /api/admin/products:
    post:
      tags:
        - Produtos
      summary: Cria um novo produto
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/product"
      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product"
components:
  schemas:
    category:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        status:
          type: string
    putCategory:
      type: object
      properties:
        nome:
          type: string
        status:
          type: string
    categories:
      type: array
      items:
        $ref: "#/components/schemas/category"
    product:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        descricao:
          type: string
        slug:
          type: string
        precoUnitario:
          type: string
        quantidade:
          type: integer
        categoriaId:
          type: integer